kind: pipeline
type: docker
name: default

steps:
- name: build
  image: rust:latest
  commands:
  - cargo build --release --verbose --all  

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: 
      - target/release/voj-ctl
  when:
    event: tag
    
